name: Copia de seguridad y ejecución
on:
  push:
jobs:
 backup_y_accion:
 runs-on: ubuntu-latest
 
 steps:
 # 1. Descargar el código del repositorio
 - name: Checkout del repositorio
 uses: actions/checkout@v5
 # 2. Crear carpeta backup
 - name: Crear copia de seguridad
 run: |
   mkdir -p backup
   cp -r datos backup/
 # 3. Realizar otra acción: comprimir la copia
   - name: Comprimir carpeta de backup
   run: | 
    -czf backup.tar.gz backup
   
  # 4. Subir el archivo como artefacto  
  - name: Subir artefacto
   uses: actions/upload-artifact@v5
   with:
    name: copia-seguridad
    path: backup.tar.gz